[package]
name = "analogz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "analogz"
crate-type = ["cdylib"]

[dependencies]
itertools = "0.14.0"
num_cpus = "1.17.0"
pyo3 = "0.25.0"
