[package]
name = "analogz"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
dateparser = "0.2.1"
itertools = "0.14.0"
num_cpus = "1.17.0"
polars = "0.49.1"
pyo3 = { version = "0.25.0", features = ["full"] }
rayon = "1.10.0"
regex = "1.11.1"
